name: 'Bug report (YAML)'
description: 'Report a bug using a structured form'
title: '[Bug] '
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the following fields to help us investigate the bug.
  - type: input
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug
      placeholder: 'A clear and concise description of what the bug is.'
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: How can we reproduce the bug?
      placeholder: |
        1. Go to '...'
        2. Run command '...'
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Screenshots or logs
      description: Add screenshots or log snippets if applicable.
    validations:
      required: false
  - type: input
    id: environment
    attributes:
      label: Environment
      description: e.g. OS, Node.js version, i18n-excel-manager version
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Any other context about the problem?
    validations:
      required: false
