blank_issues_enabled: false
contact_links:
  - name: verbatra repository
    url: https://github.com/mariokreitz/verbatra
    about: This project is deprecated. Use verbatra for ongoing development.
  - name: verbatra issues
    url: https://github.com/mariokreitz/verbatra/issues
    about: Please file bugs and feature requests in verbatra.
  - name: verbatra documentation
    url: https://www.verbatra.kreitz-webdev.de/
    about: Official documentation for verbatra.
