name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
      - run: npm run format:check
      - name: Run unit tests
        run: npm test
      - name: Run tests with coverage (enforced >=85%)
        run: npm run test:coverage
      - name: List coverage outputs
        if: always()
        run: |
          ls -la coverage || true
          find coverage -maxdepth 2 -type f -print | sort || true
      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.node-version }}-${{ github.sha }}
          if-no-files-found: ignore
          retention-days: 7
          path: |
            coverage/**
            coverage/coverage-summary.json
            coverage/lcov.info
